"""initial models: Site, Microphone, Recording, Detection

Revision ID: 76e200341ff6
Revises: 
Create Date: 2026-06-08 08:24:14.574747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '76e200341ff6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False), # type: ignore[attr-defined]
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore[attr-defined]
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_name'), 'site', ['name'], unique=False)
    op.create_table('microphone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False), # type: ignore[attr-defined]
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microphone_name'), 'microphone', ['name'], unique=False)
    op.create_table('recording',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('microphone_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore[attr-defined]
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore[attr-defined]
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore[attr-defined]
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True), # type: ignore[attr-defined]
    sa.ForeignKeyConstraint(['microphone_id'], ['microphone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore[attr-defined]
    sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore[attr-defined]
    sa.Column('scientific_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # type: ignore[attr-defined]
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection')
    op.drop_table('recording')
    op.drop_index(op.f('ix_microphone_name'), table_name='microphone')
    op.drop_table('microphone')
    op.drop_index(op.f('ix_site_name'), table_name='site')
    op.drop_table('site')
    # ### end Alembic commands ###
